# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import nutbox_bot_pb2 as nutbox__bot__pb2


class NutboxBotStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushMessage = channel.unary_unary(
                '/nutbox_bot.NutboxBot/PushMessage',
                request_serializer=nutbox__bot__pb2.PushMessageRequest.SerializeToString,
                response_deserializer=nutbox__bot__pb2.BaseReply.FromString,
                )


class NutboxBotServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PushMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NutboxBotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PushMessage,
                    request_deserializer=nutbox__bot__pb2.PushMessageRequest.FromString,
                    response_serializer=nutbox__bot__pb2.BaseReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nutbox_bot.NutboxBot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NutboxBot(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nutbox_bot.NutboxBot/PushMessage',
            nutbox__bot__pb2.PushMessageRequest.SerializeToString,
            nutbox__bot__pb2.BaseReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
