# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nutbox_bot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10nutbox_bot.proto\x12\nnutbox_bot\x1a\x1cgoogle/api/annotations.proto\"6\n\x12PushMessageRequest\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\tBaseReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t2t\n\tNutboxBot\x12g\n\x0bPushMessage\x12\x1e.nutbox_bot.PushMessageRequest\x1a\x15.nutbox_bot.BaseReply\"!\x82\xd3\xe4\x93\x02\x1b\"\x16/v1/common/pushmessage:\x01*b\x06proto3')



_PUSHMESSAGEREQUEST = DESCRIPTOR.message_types_by_name['PushMessageRequest']
_BASEREPLY = DESCRIPTOR.message_types_by_name['BaseReply']
PushMessageRequest = _reflection.GeneratedProtocolMessageType('PushMessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUSHMESSAGEREQUEST,
  '__module__' : 'nutbox_bot_pb2'
  # @@protoc_insertion_point(class_scope:nutbox_bot.PushMessageRequest)
  })
_sym_db.RegisterMessage(PushMessageRequest)

BaseReply = _reflection.GeneratedProtocolMessageType('BaseReply', (_message.Message,), {
  'DESCRIPTOR' : _BASEREPLY,
  '__module__' : 'nutbox_bot_pb2'
  # @@protoc_insertion_point(class_scope:nutbox_bot.BaseReply)
  })
_sym_db.RegisterMessage(BaseReply)

_NUTBOXBOT = DESCRIPTOR.services_by_name['NutboxBot']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NUTBOXBOT.methods_by_name['PushMessage']._options = None
  _NUTBOXBOT.methods_by_name['PushMessage']._serialized_options = b'\202\323\344\223\002\033\"\026/v1/common/pushmessage:\001*'
  _PUSHMESSAGEREQUEST._serialized_start=62
  _PUSHMESSAGEREQUEST._serialized_end=116
  _BASEREPLY._serialized_start=118
  _BASEREPLY._serialized_end=156
  _NUTBOXBOT._serialized_start=158
  _NUTBOXBOT._serialized_end=274
# @@protoc_insertion_point(module_scope)
